// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Request struct {
	Secret string  `json:"Secret"`
	Type   string  `json:"Type,options=len|float|sort|nums"`
	End    string  `json:"End"`
	Arr    []int64 `json:"Arr"`
}

type Response struct {
	Data string `json:"Data"`
}
