// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"random/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/arr",
				Handler: ArrHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/arrRet",
				Handler: ArrRetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/float",
				Handler: FloatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/int",
				Handler: IntHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/lottery",
				Handler: LotteryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/puke",
				Handler: PukeHandler(serverCtx),
			},
		},
	)
}
